{"name": "test_appium_connection", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))", "trace": "venv\\Lib\\site-packages\\urllib3\\connectionpool.py:787: in urlopen\n    response = self._make_request(\nvenv\\Lib\\site-packages\\urllib3\\connectionpool.py:534: in _make_request\n    response = conn.getresponse()\nvenv\\Lib\\site-packages\\urllib3\\connection.py:565: in getresponse\n    httplib_response = super().getresponse()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\client.py:1395: in getresponse\n    response.begin()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\client.py:325: in begin\n    version, status, reason = self._read_status()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\client.py:286: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\socket.py:706: in readinto\n    return self._sock.recv_into(b)\nE   ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다\n\nDuring handling of the above exception, another exception occurred:\nconftest.py:93: in appium_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723\", options=options)\nvenv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py:257: in __init__\n    super().__init__(\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:208: in __init__\n    self.start_session(capabilities)\nvenv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py:346: in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:345: in execute\n    response = self.command_executor.execute(driver_command, params)\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:300: in execute\n    return self._request(command_info[0], url, body=data)\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:321: in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\nvenv\\Lib\\site-packages\\urllib3\\_request_methods.py:143: in request\n    return self.request_encode_body(\nvenv\\Lib\\site-packages\\urllib3\\_request_methods.py:278: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\nvenv\\Lib\\site-packages\\urllib3\\poolmanager.py:459: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\nvenv\\Lib\\site-packages\\urllib3\\connectionpool.py:841: in urlopen\n    retries = retries.increment(\nvenv\\Lib\\site-packages\\urllib3\\util\\retry.py:474: in increment\n    raise reraise(type(error), error, _stacktrace)\nvenv\\Lib\\site-packages\\urllib3\\util\\util.py:38: in reraise\n    raise value.with_traceback(tb)\nvenv\\Lib\\site-packages\\urllib3\\connectionpool.py:787: in urlopen\n    response = self._make_request(\nvenv\\Lib\\site-packages\\urllib3\\connectionpool.py:534: in _make_request\n    response = conn.getresponse()\nvenv\\Lib\\site-packages\\urllib3\\connection.py:565: in getresponse\n    httplib_response = super().getresponse()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\client.py:1395: in getresponse\n    response.begin()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\client.py:325: in begin\n    version, status, reason = self._read_status()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\http\\client.py:286: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\socket.py:706: in readinto\n    return self._sock.recv_into(b)\nE   urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '현재 연결은 원격 호스트에 의해 강제로 끊겼습니다', None, 10054, None))"}, "description": "Appium 드라이버 연결 테스트", "attachments": [{"name": "log", "source": "0089db7e-f66f-4ebb-910a-02cd05089152-attachment.txt", "type": "text/plain"}], "start": 1760865686510, "stop": 1760865686510, "uuid": "983fcf1a-5d85-40b8-a4d4-cf953e014433", "historyId": "e2d0481e0d71a6f6e99d6306bbb33f80", "testCaseId": "e2d0481e0d71a6f6e99d6306bbb33f80", "fullName": "appium.tests.test_appium_connection#test_appium_connection", "labels": [{"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "appium.tests"}, {"name": "suite", "value": "test_appium_connection"}, {"name": "host", "value": "DESKTOP-27T24JT"}, {"name": "thread", "value": "17132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "appium.tests.test_appium_connection"}]}