{"uuid": "630ec50c-0904-4359-9f3b-fada56adbaa5", "children": ["47e4f532-22c5-456f-9a73-ed5db5c01f0a"], "befores": [{"name": "appium_driver", "status": "skipped", "statusDetails": {"message": "Skipped: Appium 연결 실패: Message: Could not find a connected Android device in 20000ms\nStacktrace:\nUnknownError: Could not find a connected Android device in 20000ms\n    at getResponseForW3CError (C:\\Users\\tslee\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.ts:1103:34)\n    at asyncHandler (C:\\Users\\tslee\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.ts:507:57)\nThe above error is caused by\nError: Could not find a connected Android device in 20000ms\n    at ADB.getDevicesWithRetry (C:\\Users\\tslee\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-adb\\lib\\tools\\system-calls.js:295:13)\n    at AndroidUiautomator2Driver.getDeviceInfoFromCaps (C:\\Users\\tslee\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\device\\common.js:41:21)\n    at AndroidUiautomator2Driver.createSession (C:\\Users\\tslee\\.appium\\node_modules\\appium-uiautomator2-driver\\lib\\driver.ts:361:30)\n    at AppiumDriver.createSession (C:\\Users\\tslee\\AppData\\Roaming\\npm\\node_modules\\appium\\lib\\appium.js:360:35)\n", "trace": "  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\conftest.py\", line 100, in appium_driver\n    pytest.skip(f\"Appium 연결 실패: {str(e)}\")\n  File \"C:\\Users\\tslee\\Desktop\\김선아\\ddokta-e2e-automation\\venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 179, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n"}, "start": 1760879579200, "stop": 1760879599288}], "start": 1760879579200, "stop": 1760879599292}